services:
  app-node:
    build: .
    container_name: app-node
    image: app-node:latest
    user: node
    working_dir: /var/www/app
    # environment:
    #   - NODE_ENV=production
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/var/www/app
    ports:
      - '3000:3000'
      - '5173:5173'
    restart: always
    # command: node backend/dist/server.js
    command: 'tail -f /dev/null'
    depends_on:
      - mailsandbox
  mailsandbox:
    container_name: mailsandbox
    image: mailhog/mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
